num_tasks = 13
num_rollouts = 2
max_concurrent = 2
push = false

[env.taskset]
id = "carla-env"
modality = "text"

[env.taskset.task.tools]
colocated = false

[env.taskset.task.tools.runtime]
type = "prime"
image = "sinatras/carla-env-runtime@sha256:e7d14c3ced7cec518872067a9b00f10f1352e781b8f4b6028adb41323593d331"
workdir = "/home/carla"
vm = false
region = "us"
cpu = 4
memory = 8
disk = 40

[env.agent.harness]
id = "null"

[env.agent.runtime]
type = "prime"
vm = true

[env.agent.timeout]
setup = 600
rollout = 600
finalize = 120
