num_tasks = 13
num_rollouts = 2
max_concurrent = 1
push = false

[env.taskset]
id = "carla-env"
modality = "vision"

[env.taskset.task.tools]
colocated = false

[env.taskset.task.tools.runtime]
type = "docker"
image = "sinatras/carla-env-runtime@sha256:e3af793c6e8262bcd421dc67dd832de4959044e0003eceaed6f759cba84839d0"
workdir = "/home/carla"
cpu = 4
memory = 8
gpu = "1"

[env.agent.harness]
id = "null"

[env.agent.runtime]
type = "prime"
vm = true

[env.agent.timeout]
setup = 600
rollout = 600
finalize = 120
