num_tasks = 19
num_rollouts = 2
max_concurrent = 1
push = false

[env.taskset]
id = "carla-env"
modality = "vision"
families = ["decision", "maze", "navigation", "free_roam"]
seeds = [0, 1]

[env.taskset.task.tools]
colocated = false

[env.taskset.task.tools.runtime]
type = "docker"
image = "sinatras/carla-env-runtime@sha256:1de41898269de257c9a8dc90626c9ad93a655129f4eec77d26c5113bb2440331"
workdir = "/home/carla"
cpu = 4
memory = 8
gpu = "1"

[env.agent.harness]
id = "null"

[env.agent.runtime]
type = "prime"
vm = true

[env.agent.timeout]
setup = 600
rollout = 600
finalize = 120
